### ISSUE TITLE
Question about usability and planning.

### ISSUE THREAD

**Issue by csajedi** [status-im/nim-libp2p#102]
I am loving nim so far and want to use it to experiment with p2p technology, for that reason I was really thrilled to see you've won a grant to actually rewrite this in nim instead of using a wrapper. I want to inquire about intentions for this repository and its current state - is now a good time for me to begin to experiment with it, or will you implement a tagged release system that will signal that the library is ready for general use. I've had mixed luck with the provided examples. 

Finally, will it support compilation to the js backend (especially interested in browser).

**Comment by dryajov** [comment]
Hi and welcome @csajedi!

> I want to inquire about intentions for this repository and its current state 

Currently the library is still under heavy development and it will most likely remain in alpha for the next few months. However we're beginning to use it in our eth2 implementation (called `nim-beacon-chain`) and we expect this integration to help drive further development and stability efforts. In other words, this library will start seeing some real world usage, furthermore we expect it to be in production some time this year.

>  is now a good time for me to begin to experiment with it

It depends on what you mean by experiment. If you are looking at building something production quality, it is probably a bit premature (however see previous paragraph). If what you're after is learning/playing with some code, then this is probably as good of a time as any; we're actively looking for both community feedback as well as contributions in the form of bug fixes and missing features (please make sure to check out the issues), documentation and general feedback. That said, do expect things to break and the api to change from time to time. 

> implement a tagged release system that will signal that the library is ready for general use

We can't promise that we'll be shipping any binaries any time soon if that's what you mean, but we'll do our best to communicate when the library reaches beta and subsequently a stable version. It is however extremely easy to get started with what's there already. Follow the instructions in the readme and you should be able to get started in no time, and don't hesitate to ask questions, we'll do our best to respond. 

Hope this helps and please report any issues or feedback, it will be much appreciated!

**Comment by dryajov** [comment]
> Finally, will it support compilation to the js backend (especially interested in browser).

This is one of the goals eventually, but not just yet. There shouldn't be anything in the core of the library that would prevent it from running in the browser besides the lack of browser native transport; websockets and/or WebRTC. Once those are added then it should be possible to run in the browser. 

However, if there is interest I encourage the community to pick this up, there are a few benefits 1) it would be a great way of getting aquatinted with all the parts of nim-libp2p and 2) it would be a huge win all around given the massive deployment of browsers as a platform.

In very broad strokes, I would first make this run in Node, which should not require anything additional to make it work and subsequently we can add the transports listed above.

**Comment by mratsim** [comment]
Note that @tina1998612 is currently writing an introductory blog post on how to use nim-libp2p, if you want some specific examples that might give her some ideas.

**Comment by arnetheduck** [comment]
> js backend

more sane would be a wasm port - the JS backend feels a bit dated at this point to be sinking resources into.

**Comment by dryajov** [comment]
> > js backend
> 
> more sane would be a wasm port - the JS backend feels a bit dated at this point to be sinking resources into.

Depends on the effort, the assumption is that it will be minimal. If it ends up being too big of an effort then yes, it doesn't make much sense at this point.

**Comment by csajedi** [comment]
Thanks for all the responses. I am playing around with the library now, also working to wrap [humblenet](https://github.com/HumbleNet/HumbleNet). It may prove useful for your this, since the browser is a target for compilation (and through emscripten instead of js backend). Follow progress [here](https://github.com/csajedi/Humblenet.nim) for now.

**Comment by dryajov** [comment]
I think this is a good info issue, should maybe stay open for others that might come here and have similar questions?
