### ISSUE TITLE
`noise` and `secio` framing broken for large payloads

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#114]
https://github.com/status-im/nim-libp2p/blob/a2acdd7933ff411bb6f4133d90bb46caec6127dc/libp2p/protocols/secure/secio.nim#L186

https://github.com/status-im/nim-libp2p/blob/a2acdd7933ff411bb6f4133d90bb46caec6127dc/libp2p/protocols/secure/noise.nim#L434

in both cases, `writeMessage` fails to consider that the given payload may be larger than the frame size of the protocol (8mb, 65kb respectively)

**Comment by sinkingsugar** [comment]
I swear I had exceptions in noise.. I must have removed them when fixing the integration tests.
But yes I knew this... the thing is that there is no real spec... go implements some packets fragmentation (broken) rust does nothing about it (afaik)

**Comment by arnetheduck** [comment]
why would you have exceptions for this case? the implementation should simply split the given payload into multiple fragments, no?

**Comment by sinkingsugar** [comment]
Because there is no clear spec on how that fragmentation should happen really, like where do you write the full size of the message, considering that plain len includes the "noise" and encrypted len is the overflowing one?

**Comment by arnetheduck** [comment]
abstractly, it's a stream - it has no messages. you will have to account for any additional noise framing when splitting the message up. `readMessage`/`writeMessage` are poorly named, they should be called something like `readData`. the fragmentation is basically to split the data into pieces that the framing can support - just like when you send a 1gb file over tcp, it will be fragmented into little 1.4kb packets, each with its own header.

**Comment by sinkingsugar** [comment]
I get what you mean but I don't think it fits https://github.com/libp2p/specs/tree/master/noise#wire-format 
I mean what you said can be done but it would work for us and maybe others.. but maybe not cos someone might interpret the spec in a different way thinking in "message"

e.g.
> The noise_message field contains a Noise Message as defined in the Noise spec, which has a maximum length of 65535 bytes.

**Comment by sinkingsugar** [comment]
Altho 
> All data is segmented into messages with the following structure
Might imply fragments, I wish this was more explicit honestly tho.

**Comment by arnetheduck** [comment]
I'm not sure what you mean - there are two things going on here:

* LPStream has a write method that allows you to write an arbitrary number of bytes in a single call - - there is no concept of "message" here - just bytes - 1 or many - it doesn't matter if you call write once with 2 bytes or twice with 1 byte - the end result on the other end should be the same. In our implementation, the write method effectively delegates the writing to `writeMessage` through a maze of abstractions but the important part is that whoever calls `write` has no idea about these underlying frame sizes.

* noise and secio have frames, but this is an implementation detail - these frames are limited in size - 8mb for secio and 64kb for noise - whatever we send out from these protocols has to adhere to these limits - in secio, because of an explicit limit, in noise because the wire format simply doesn't support larger frames. it follows that it's the responsibility of noise to take the stream of data it gets from the application and repackage it into noise frames when writing, then reconstruct the stream of bytes when it does the reading.

**Comment by sinkingsugar** [comment]
well I get it, I guess I keep forgetting that libp2p implicitly is always "streams" anyway. 
So my doubts were kinda pointless. And like you pointed anyway `Connection` is an `LPStream`

**Comment by dryajov** [comment]
I think this means that we should fragment the stream of data on frame boundaries - 8mb and 64kb respectively. When streaming, once we reach the a frame boundary it should be sent out/flushed and another should be started right after that. 

This only happens for chunks that are larger than the frame size.

**Comment by sinkingsugar** [comment]
Noise now can:
https://github.com/status-im/nim-libp2p/commit/1550bea1cc787b3ed1f5fea4a32896e68ebc7a22
I agree with @arnetheduck and that probably was one thing that mislead-ed me too, the `writeMessage`/`readMessage` API is confusing due to actually being a stream.

**Comment by sinkingsugar** [comment]
Btw should we implement fragmentation even in mplex? @dryajov 
It has a smaller frame size, I think 1mb, I didn't think about that when adding the limit

**Comment by sinkingsugar** [comment]
Btw we have another issue with big sizes (more then 0x1200000), getting a `Exception message: wrong varint size`

**Comment by sinkingsugar** [comment]
Ah we have a hard limt on `DefaultReadSize` in `Connection.nim`
So implementing this for secio was pointless, I will push it anyway tho.

**Comment by arnetheduck** [comment]
> DefaultReadSize

this looks wrong - it's a helper method to read a varint-prefixed message which seem pretty common, but being a "generic" helper it should probably take the max length as a parameter

**Comment by sinkingsugar** [comment]
I agree, some users might want to go over the limits I suppose

**Comment by sinkingsugar** [comment]
All fixed in here 
https://github.com/status-im/nim-libp2p/pull/117
