### ISSUE TITLE
Less confusing init patterns

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-libp2p#120]
Just an idea to make the api more intuitive about resource management.

### Init patterns

While trying to figure out why many tests were failing in the `test-stream` branch, I noticed that the resource creation and destruction API is counter-intuitive.
Most of the debugged issues were just lingering resources in the tests.

We are networking library so it's very common that *releasing* resources is spelled with `close()` and actually this is the case.
Yet most of those resources are created with a `newXX` pattern while the most natural would be `openXX`, so when we write code we can mentally automatically think and write stuff like, I know this pattern often will not be of use unless its a test but it still matters
```nim
let mplexDial = openMplex(conn)
# e.g. in the case of a test
defer: await mplexDial.close()
```
Without the need of thinking anything and without the need of any linter (very broken in nim) because we know already that a `open` has a `close`.

Also `new` is often associated with *forget me* `ref` objects.

------

### new pattern research
```
131: newSeq
184: newException
2: newSkContext
43: newConnection
17: newDaemonApi
1: newStringTable
3: newStringOfCap
47: newFuture
1: newPool
7: newAsyncEvent
7: newString
2: newMultistreamHandshakeException
22: newMultistream
2: newInvalidVarintException
1: newInvalidVarintSizeException
2: newChannel
16: newLPStreamEOFError
3: newStreamInternal
4: newLPStreamLimitError
21: newMplex
13: newStream
4: newMuxer
5: newMuxerProvider
9: newSeqOfCap
9: newIdentify
4: newMessage
5: newTimedCache
6: newMCache
3: newAsyncLock
15: newPubSub
63: newBufferStream
12: newPubSubPeer
9: newNoise
2: newPlainText
2: newSecioConn
4: newSecio
7: newStandardSwitch
48: newTransport
5: newSwitch
2: newAlreadyPipedError
4: newNotWritableError
8: newLPStreamIncompleteError
2: newChronosStream
2: newAsyncStreamReader
2: newAsyncStreamWriter
6: newLPStreamReadError
9: newLPStreamIncorrectError
4: newLPStreamWriteError
6: newNoPubSubException
3: newTestSelectStream
2: newTestLsStream
2: newTestNaStream
```

**Comment by arnetheduck** [comment]
generally, I'm thinking that `func init(T: type X, ....)` should be used for construction that cannot fail - `x.open(...)` can fail and would be part of a 2-phase init, where you have "ready" and "open" as states -`init` goes to "ready" and `open` goes to "open", and "close" goes back to "ready"...

`newXxx` has the problem that it cannot be used in generic code, which is one reason why it might be a good idea to port legacy code to a unified "init" pattern - but this should always succeed or we'll quickly run into exception-safety features and leaks.

**Comment by dryajov** [comment]
@sinkingsugar I generally agree with @arnetheduck on this one and most objects in libp2p use `close` to reset the state to `ready` and it should be _generally possible_ to continue using the objects after close (not recommended however, since it hasn't been properly tested). Once we add `destructors`, there will be a clear distinction between object construction/destruction and `open/closed` states. In summary, `close` stands for *release resources and reset the object to its initial state*.

**Comment by sinkingsugar** [comment]
That's cool, 
I mean the whole point of this issue was indeed trying to figure out a pattern that can be documented and be consistent.

I'm still quite unsure about `init` and `ref` types, also while investigating memory allocators I needed to refactor every single type to be value type because we declare all `ref object` ( which is a bad habit really in the long run ).

**Comment by dryajov** [comment]
Should generally adhere to the style guide outline in https://github.com/status-im/nimbus-eth2/pull/2249
