### ISSUE TITLE
Gossipsub internal tests

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-libp2p#129]
https://github.com/status-im/nim-libp2p/blob/3514733060f2f10e757b6d6e0fcd5646437bebee/libp2p/protocols/pubsub/gossipsub.nim#L448-L454

I casually ran them and found an issue
https://github.com/status-im/nim-libp2p/commit/3514733060f2f10e757b6d6e0fcd5646437bebee

I think they should be added to nimble test/CI
Any objection? @dryajov

**Comment by sinkingsugar** [comment]
Actually they are in nimble test, but in nimble test we only test release missing all nim `assert` calls.
Maybe we should also run debug of at least our native tests ?

**Comment by sinkingsugar** [comment]
With added I mean in fact to remove the `and not defined(release)` cos nimble test passes `-d:release`

**Comment by dryajov** [comment]
@sinkingsugar yes it was meant to be enable, but I think I changed `nimble test` to run in release mode and inadvertently disabled them, either way they should be on.
