### ISSUE TITLE
pubsub message information.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-libp2p#153]
Current version of `nim-libp2p` provides pretty simple interface for messages got received via `pubsub` protocols.

https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L25-L26

So only topic name and message data is shared, but it would be very handy to get access to all fields:
https://github.com/libp2p/go-libp2p-daemon/blob/master/pb/p2pd.proto#L147-L152

1. optional bytes from 
2. optional bytes seqno
3. optional bytes signature
4. optional bytes key

**Comment by dryajov** [comment]
related to #155

**Comment by sinkingsugar** [comment]
This is already exposed from `Message` hooked using observers.
I suppose we can close this too

**Comment by dryajov** [comment]
closed by #156
