### ISSUE TITLE
Gossipsub 1.1

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#185]
For eth2, GossipSub 1.1 has become a high-priority item to implement, for maintaining network resilience as it resolves many security-related issues with the existing protocol:

https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md

We should implement it - considering which of these can be backported to 1.0 as well.

**Comment by dryajov** [comment]
Closing because already implemented in #240
