### ISSUE TITLE
Can't Load Daemon - Need Shared Lib?

### ISSUE THREAD

**Issue by TensorTom** [status-im/nim-libp2p#21]
I try to run the chat.nim example. It gives me: `Could not find daemon executable!` . So I compile `daemonapi.nim` but same error. So I add `daemonapi` executable to PATH but same error.

So finally I look in code and he expects `p2pd` on line 28 of daemonapi.nim but p2pd is not part of repo. Is this module using ipfs on its own or ipfs has to already be running on machine? I wanted to use him standalone in my application.

thanks

**Comment by TensorTom** [comment]
Just saw this: https://github.com/libp2p/go-libp2p-daemon/issues/20

Can we somehow add him as this?

**Comment by cheatfate** [comment]
@TensorTom right now you need to build `go-libp2p-daemon` and `daemon executable` is exactly `go-libp2p-daemon` binary.
