### ISSUE TITLE
Secured connection might be nil

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-libp2p#221]
https://github.com/status-im/nim-libp2p/blob/0d81acafa82c48b8603369fa92569eb86a0a0fac/libp2p/protocols/secure/secure.nim#L53

This leads to some `failed to dispatch method` confusing error/exception. (caused by likely some `.close()`)

Maybe a `Future[Result[Connection,cstring]]` is in order here.

**Comment by dryajov** [comment]
Any logs/steps to reproduce this?

**Comment by sinkingsugar** [comment]
It was happening quite systematically during noise tests, as long as there was a `catchable` failure within the handshake.

**Comment by dryajov** [comment]
how does this happen, because I can't repro it with fe828d87d8a1eb4c018400fe525e127c2c0401c3 (current head as of writting)

**Comment by sinkingsugar** [comment]
Well, I fixed my crashing code. 
I could make a branch with the errors in place to trigger it I guess.

**Comment by dryajov** [comment]
So is this still an issue?

**Comment by sinkingsugar** [comment]
Potentially yes.
But consider it minor as nothing seems to trigger it so far.
I opened this issue to not forget about it tho, will look into it.
I should have added a commit hash to repro it tho, my bad, will try to add more info..
