### ISSUE TITLE
Noise & Secio CI testing improvements

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-libp2p#233]
Lets not do this. Better parametrize the test and run them twice, once with noise once with secio.

_Originally posted by @dryajov in https://github.com/status-im/nim-libp2p/pull/226_

**Comment by dryajov** [comment]
@sinkingsugar is this still something we want to address or have we already covered most of the issues? Keep in mind that we don't need secio anymore.

**Comment by Menduist** [comment]
Closing, feel free to reopen if needed
