### ISSUE TITLE
[SEC] Multiple ASN.1 decoding/encoding issues

### ISSUE THREAD

**Issue by pornin** [status-im/nim-libp2p#296]
Tags: nbc-audit-2020-0, difficulty:medium, severity:medium, bug

There are a number of unhandled edge cases in the ASN.1 encoding/decoding code in [minasn1.nim](https://github.com/status-im/nim-libp2p/blob/master/libp2p/crypto/minasn1.nim). They can lead to incorrect encodings in produced objects, input values improperly decoded, and in some cases out-of-bounds read accesses which may trigger an uncaught exception or a fatal error. If the decoding functions are applied on externally received and as yet unverified data, this can lead to, at least, denial-of-service attacks.

In [`asn1EncodeLength`, line 166](https://github.com/status-im/nim-libp2p/blob/0f06ae5a1dbb7294c802a29e915ed190bbc25331/libp2p/crypto/minasn1.nim#L166):
```
  if length < 0x80:
    if len(dest) >= 1:
      dest[0] = cast[byte](length)
      result = 1
  else:
```
If `len(dest)` is zero (caller did not provide an output buffer, presumably to get the required length first, for allocation purposes) and `length` is less than 128, then `result` is not set. The function returns 0, instead of the expected value 1 (the length would be encoded over 1 byte).

In [`asn1EncodeInteger`, line 211](https://github.com/status-im/nim-libp2p/blob/0f06ae5a1dbb7294c802a29e915ed190bbc25331/libp2p/crypto/minasn1.nim#L210):
```
    if value[o] >= 0x80'u8:
      dest[1 + lenlen] = 0x00'u8
      s = 2
    if len(value) > 0:
      copyMem(addr dest[s + lenlen], unsafeAddr value[o], len(value) - o)
```
The `o` index is set (earlier in the function) to the index of the first non-zero byte in the `value` array (or to the index of the last byte, in case all bytes are zero). However, the function also accepts a zero-length array as input; this is even tested explicitly in the final `if`. If `value` has length zero, `o` has value zero, and the access `value[o]` is out-of-bounds and should trigger an exception or a fatal error. Note that a zero-length value array can plausibly happen if the integer was decoded with the same library, since decoding of integers strips a leading byte of value 0x00. Also, notice that even if the `value[o]` does not crash, then the `copyMem()` won't happen and the second byte of the encoding (which should be set to 0x00) will remain unset.

In [`asn1EncodeBitString`, line 291](https://github.com/status-im/nim-libp2p/blob/0f06ae5a1dbb7294c802a29e915ed190bbc25331/libp2p/crypto/minasn1.nim#L291):
```
      copyMem(addr dest[2 + lenlen], unsafeAddr value[0], len(value))
```
The value bytes are copied as-is. However, if there are ignored bits in the last byte, then the corresponding bits in the encoding should be set to zero, as per DER rules (leaving unspecified values would be fine for BER, but DER is more restrictive). Also, depending on the source of the `BIT STRING`, these bits might contain sensitive values, and thus should be trimmed explicitly.

In [`asn1EncodeOid`, line 329](https://github.com/status-im/nim-libp2p/blob/0f06ae5a1dbb7294c802a29e915ed190bbc25331/libp2p/crypto/minasn1.nim#L329):
```
  doAssert(value[0] >= 1 and value[0] < 2)
  doAssert(value[1] >= 1 and value[1] <= 39)
```
These rules are too restrictive and make the function incapable of encoding some common OIDs, including most of those used in X.509 certificates, or all the OIDs defined by NIST for, for instance, AES encryption. The code requires the first component to be equal to 1, but X.690 rules allow the first component to be 0, 1 or 2. As for the second component, it can have value 0, and, if the first OID component has value 2, the second component can range to arbitrary high values (for instance, 2.52 [has been allocated](http://www.oid-info.com/cgi-bin/display?oid=2.52&action=display)). (Most OID-encoding activity in practical code will probably use the other `asn1EncodeOid` function, which takes an already-encoded constant blob and thus avoids all these issues.)

In [`asn1EncodeContextTag`, line 409](https://github.com/status-im/nim-libp2p/blob/0f06ae5a1dbb7294c802a29e915ed190bbc25331/libp2p/crypto/minasn1.nim#L409):
```
    dest[0] = 0xA0'u8 or (cast[byte](tag) and 0x0F)
```
The contextual tag value is truncated to 4 bits, limiting the possible values to the 0..15 range. This is probably sufficient for practical purposes in cryptography-related protocols, but, in all generality, the value of a contextual tag may range to unlimited values. The truncation to 4 bits should be documented. Note that values 31 and higher would lead to a multibyte encoding for the tag, which the decoding functions do not support (see `getTag()`, lines 445-446).

In [`read`, line 501](https://github.com/status-im/nim-libp2p/blob/0f06ae5a1dbb7294c802a29e915ed190bbc25331/libp2p/crypto/minasn1.nim#L501):
```
        # INTEGER
        if not ab.isEnough(cast[int](length)):
          return err(Asn1Error.Incomplete)
        if ab.buffer[ab.offset] == 0x00'u8:
          length -= 1
          ab.offset += 1
```
If the input already has length zero (which is nominally invalid for an `INTEGER`, but not checked by the code), then the value may be located at the very end of the input buffer. The `isEnough` call (actually a template) won't see any problem to it, but the access `ab.buffer[ab.offset]` will be out-of-bounds and may trigger a runtime exception or a fatal error.

Also, since the code removes a leading `0x00` byte, it cannot reliably distinguish between a negative or positive integer; e.g. it will return the exact same bytes for an encoded 255 and an encoded -1. We can also note that the removal of a leading byte of value 0x00 means that if the input integer is zero, then the returned value will be a zero-length array, thereby making it more probable to trigger the out-of-bounds access described earlier (in `asn1EncodeInteger`).

Still in [`read`, line 518](https://github.com/status-im/nim-libp2p/blob/0f06ae5a1dbb7294c802a29e915ed190bbc25331/libp2p/crypto/minasn1.nim#L518):
```
        # BIT STRING
        if not ab.isEnough(cast[int](length)):
          return err(Asn1Error.Incomplete)
        field = Asn1Field(kind: Asn1Tag.BitString, klass: klass,
                          index: ttag, offset: cast[int](ab.offset + 1),
                          length: cast[int](length - 1))
        shallowCopy(field.buffer, ab.buffer)
        field.ubits = cast[int](((length - 1) shl 3) - ab.buffer[ab.offset])
        ab.offset += cast[int](length)
        return ok(field)
```
As in the case of integer values, the length of an encoded `BIT STRING` cannot be zero, but this is not checked by the code. The first byte of an encoded `BIT STRING` contains the number of bits that should be ignored in the last value byte. The code above misses two checks:
  - If the `length` is zero, then the returned `field.length` will be -1; moreover, the access `ab.buffer[ab.offset]` can be out-of-bounds and trigger a runtime exception or a fatal alert, as previously described for `INTEGER` values.
  - The number of ignored bits shall be between 0 and 7; if the encoded length is 1 (that is, the encoded value contains _only_ the number of ignored bits, no actual data), then the number of ignored bits shall be 0. Since the code does not check these properties, the returned `field.ubits` may be lower than expected, and possibly negative.

**Comment by eschorn1** [comment]
I have reviewed https://github.com/status-im/nim-libp2p/pull/323/files and observe the following changes:

* In `asn1EncodeLength` (originally near line 166), the function now returns the correct expected value of 1.
* In `asn1EncodeInteger` (originally near line 211), the logic has been adapted to handle a zero-length `value`.
* In `asn1EncodeBitString` (originally near line 291), the logic now sets the unused bits to zero.
* In `asn1EncodeOid` (originally near line 329), incorporates relaxed OID constraints.
* In `asn1EncodeContextTag` (originally near line 409), the limitation on tag values in [0, 15] range is documented.
* In `read` (originally near line 501), now checks for length==0 and considers leading zeros.
* In `read` (originally near line 518), now checks for length==0 and properly handles ignored bits.

The above changes address the finding, so this issue can be closed. Thank you!
