### ISSUE TITLE
Diagnostic `oid` sometimes are logged in repr form vs stringified

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-libp2p#301]
Like 
`"oid":{"time":620503391,"fuzz":1048638320,"count":1681245770}} `
oid is used to track connection, but at some places it got printed in hex, and in some places we see it like repr

**Comment by dryajov** [comment]
yes, I've seen this over and over, we need to go through the codebase and stringify it (`$oid`)

**Comment by arnetheduck** [comment]
this is fixed by `shortLog` and `formatIt`
