### ISSUE TITLE
PubSub potential message loss

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#344]
PubSub currently assumes that there will be only one `RPCMsg` message per transmission, but a client can potentially batch and send multiple `RPCMsg` per transmission. This can lead to message loss depending on weather the remote implementation batches `RPCMsg`'s or doesn't and should be handled appropriately by parsing the entire length of the buffer in `decodeRpcMsg` and subsequently handling multiple `RPCMsg`'s downstream.

**Comment by arnetheduck** [comment]
not possible, per protobuf spec
