### ISSUE TITLE
cannot generate destructor for generic type: seq[TopicHandler]

### ISSUE THREAD

**Issue by gogolxdong** [status-im/nim-libp2p#354]
root@LAPTOP-JRQP23H9:/mnt/c/nim-libp2p# nim c -r -d:release --gc:arc --hints:off --warnings:off -d:libp2p_pubsub_sign=true -d:libp2p_pubsub_verify=true  -d:chronicles_sinks:json tests/pubsub/testpubsub
/mnt/c/Users/asus/.nimble/pkgs/chronos-2.5.2/chronos/asyncmacro2.nim(259, 33) Error: cannot generate destructor for generic type: seq[TopicHandler]

**Comment by dryajov** [comment]
We aren't supporting ARC at the moment, removing `--gc:arc` works for me.

**Comment by dryajov** [comment]
Needs to be addressed, but this isn't part of v1.

**Comment by Menduist** [comment]
This has been fixed in the meantime
We also run our CI with orc daily
