### ISSUE TITLE
Gossipsub further improvements

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-libp2p#365]
The overall picture is ok, obviously likely not bug free but feature wise almost complete.

Few missing things are:
- [x] RPC `encodeMessage` - currently we threat as optional all empty fields but instead we should take better decisions, also there is this PR that will influence this: https://github.com/libp2p/specs/pull/294
- [x] RPC `decodePrune` - decode the new gossip 1.1 fields
- [ ] Changes introduced by this: https://github.com/libp2p/specs/pull/292
- [x] Extended validators: https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#extended-validators

**Comment by oskarth** [comment]
> threat as optional all empty fields but instead we should take better decision

Not sure exactly what this is referring to, but for Waku, having some of that optionality is a feature when it comes to things like metadata protection. Eth2 have slightly different design requirements I believe, so allowing for both would be useful.

**Comment by dryajov** [comment]
Most of this is implemented except the changes introduced in libp2p/specs#292, which is now tracked by #513
