### ISSUE TITLE
tests/testnative.nim fails with --threads:on

### ISSUE THREAD

**Issue by stefantalpalaru** [status-im/nim-libp2p#37]
GC-safety issues which you can see by adding a "nim.cfg" or "config.nims" containing `--threads:on` in the "tests" subdir:

```text
Hint: rpcmsg [Processing]
/mnt/sda3/storage/CODE/status/nim-beacon-chain/vendor/nim-libp2p/libp2p/crypto/ecnist.nim(885, 7) Warning: 'sign' is not GC-safe as it performs an indirect call here [GcUnsafe2]
/mnt/sda3/storage/CODE/status/nim-beacon-chain/vendor/nim-libp2p/libp2p/crypto/crypto.nim(430, 6) Warning: 'sign' is not GC-safe as it calls 'sign' [GcUnsafe2]
/mnt/sda3/storage/CODE/status/nim-beacon-chain/vendor/nim-libp2p/libp2p/protocols/pubsub/rpcmsg.nim(143, 6) Warning: 'sign' is not GC-safe as it calls 'sign' [GcUnsafe2]
/mnt/sda3/storage/CODE/status/nim-beacon-chain/vendor/nim-libp2p/libp2p/protocols/pubsub/rpcmsg.nim(171, 6) Error: 'makeMessage' is not GC-safe as it calls 'sign'
```

**Comment by zah** [comment]
I believe these issues will be traced to the fact that the imported C function from Milagro are not annotated with `gcsafe`, `noSideEffect`. It should be trivial to fix this.

**Comment by cheatfate** [comment]
This bug is not related to `nim-libp2p` it is fixed here https://github.com/status-im/nim-bearssl/commit/ca3bafb85d285f9a7d61295512e2dbc24fbf2185 and test added https://github.com/status-im/nim-libp2p/commit/80e128b0d9e222912be1f50322eb1acd8c2f1aca
