### ISSUE TITLE
Message id should be `seq[byte]`

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#380]
https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md#protobuf - message id are `bytes` in the protocol and should be `seq[byte]` in the implementation, not `string` - this affects the default message id provider as well.

**Comment by sinkingsugar** [comment]
Fine but we can argue that a `string` in nim (and even in many other languages) is just a `seq[byte]`, even the API is the same.
I think (I did not write it) the rationale here was that the id generator use string apis, so it used string.
Of course we can change it but it will just be a cast basically 😄 

In the hash cases how would you approach it btw? currently just does a `to_string`, but if we swap to bytes we could just cast the 4 bytes... altho LE/BE would matter, is that a issue? I don't think so.

**Comment by arnetheduck** [comment]
the id generator should also be `seq[byte]` - there's no reason to use a string here, it's simply wrong (string adds semantic baggage that creates confusion). hashes are for  all intents and purposes already byte sequences so they don't need more massaging

**Comment by arnetheduck** [comment]
also, `string` in protobuf is a more strict type with no `null` bytes and only valid utf-8 - this is not what this field is.

**Comment by sinkingsugar** [comment]
Regarding your last comment @arnetheduck I noticed this in the go source:
https://github.com/libp2p/go-libp2p-pubsub/blob/89f61abf299aeb209e3293034da7a0b7b318f404/pb/rpc.proto#L35
