### ISSUE TITLE
Pubsub peers not cleaned properly

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#383]
after running medalla for a bit, there's more pubsub peers than libp2p peers - this indicates there's  a race condition somewhere between libp2p peer removal and gossipsub deregistration

```
libp2p_peers 97.0
libp2p_pubsub_peers 112.0
```

**Comment by sinkingsugar** [comment]
I kept monitoring a node for 24 hours, it kept same number of peers on both metrics so far.
You still having such issue with current devel (nbc)?

**Comment by stefantalpalaru** [comment]
NBC devel on Spadina:

```text
$ curl -sS http://127.0.0.1:8008/metrics | grep -E "^(libp2p|libp2p_pubsub|nbc)_peers "
libp2p_peers 75.0
libp2p_pubsub_peers 75.0
nbc_peers 68.0
```

**Comment by sinkingsugar** [comment]
seems fine then in terms of this issue. `nbc_peers` is another story tho.

**Comment by arnetheduck** [comment]
My node has only outgoing connections - nbc c5a58555efdef09cd18d2d68b62316fedced156e:

```
libp2p_peers 103.0
libp2p_pubsub_peers 124.0
nbc_peers 79.0
```

**Comment by sinkingsugar** [comment]
Interesting.. oh I was using 1.1 btw in my long test. We might have some bug lying around indeed still.

**Comment by sinkingsugar** [comment]
I don't have this issue anymore, can see here:
https://snapshot.raintank.io/dashboard/snapshot/I5EaxGziG3nOsjXAUU47f69AUo8u8JVU?orgId=2

**Comment by sinkingsugar** [comment]
This issue has been gone for a while.
