### ISSUE TITLE
Crashes on nimbus (unhandled exception: multiaddress.nim(857, 12) `written` Merely writing a string to a buffer should always be possible)

### ISSUE THREAD

**Issue by 3esmit** [status-im/nim-libp2p#399]
I was doing normal, when suddenly crashes started to happen
![image](https://user-images.githubusercontent.com/224810/95982835-052f4800-0df7-11eb-9cfa-0362133e6a5c.png)
![image](https://user-images.githubusercontent.com/224810/95982816-fe083a00-0df6-11eb-8739-c362297d93fc.png)

**Comment by sinkingsugar** [comment]
@zah this is the `ValidIpAddress` assertion trigger issue.

**Comment by cheatfate** [comment]
This was fixed in ff48d0b1a22db46e7a93c2441d45497c8145ac74 04c95cb7b0a13f5da1ea513a770b037379f7bd13 9c1633bf871156429e042f1fe6207a00e95a6b13
