### ISSUE TITLE
Gossip1.1 does not allow publishing on topics you are not subscribed to

### ISSUE THREAD

**Issue by decanus** [status-im/nim-libp2p#440]
Currently gossip 1.1 does not allow sending on topics you are not subscribed to this is part of the spec and therefore should be enabled.

**Comment by sinkingsugar** [comment]
This should already be possible, just calling `publish`. Or the meaning of this issue is that we should disable this?

**Comment by decanus** [comment]
@sinkingsugar it does not seem possible, @dryajov and I looked into it when upgrading nim-waku to use gossip1.1 and it does not seem to work.

**Comment by dryajov** [comment]
Yeah, this seems like a regression.

**Comment by sinkingsugar** [comment]
More details would be appreciated, tests are passing on this side.

**Comment by decanus** [comment]
@sinkingsugar https://github.com/status-im/nim-waku/pull/277/files#diff-507bf8a0d65ba93873fbe4798a945913e8ce329d68f9171ded65c735b612484bR246-R250 here is the fix we had to do on our side to get it working.

**Comment by sinkingsugar** [comment]
You switched to legacy gossip 1.0, that's a workaround rather then a fix.
What kind of issues (traces/logs/messages) you had with gossip 1.1 enabled?
This is our *fanout* test, as you can see there are no subscriptions https://github.com/status-im/nim-libp2p/blob/8c8d73380f5b7ed858bd70318d47d9ee4bcb8edb/tests/pubsub/testgossipsub.nim#L374
