### ISSUE TITLE
Support lazy channels in mplex

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#46]
Channels should be opened on first use and not on create - i.e. lazy.

**Comment by sinkingsugar** [comment]
This one might need a bit of refactoring.
What's the deal with it anyway?
To for example remove this `await` from here?
https://github.com/status-im/nim-libp2p/blob/2232ca598e514ab79befac972c9ae0517b1196c3/tests/testmplex.nim#L141

**Comment by dryajov** [comment]
Lazy channels should be optional, `newStream` needs to stay async.

**Comment by sinkingsugar** [comment]
Ok, I'm still figuring things out so I'm not sure I get exactly where the *lazy* open should happen.
Like on write:
https://github.com/status-im/nim-libp2p/blob/88a030d8fbd76023354f14ff10ba740786eb46a4/tests/testmplex.nim#L142
and read:
https://github.com/status-im/nim-libp2p/blob/88a030d8fbd76023354f14ff10ba740786eb46a4/tests/testmplex.nim#L126
or during handle:
https://github.com/status-im/nim-libp2p/blob/88a030d8fbd76023354f14ff10ba740786eb46a4/libp2p/muxers/mplex/mplex.nim#L64

**Comment by dryajov** [comment]
Ah, great question. It should happen on write, the idea is that if many channels are being opened but not immediately used, we don't "spam" the remote node.

**Comment by dryajov** [comment]
closed by #78
