### ISSUE TITLE
Implement push identify

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#48]
Push identify is missing and needs to be implemented as per the spec - https://github.com/libp2p/specs/blob/master/identify/README.md#identifypush.

**Comment by sinkingsugar** [comment]
https://github.com/status-im/nim-libp2p/blob/2232ca598e514ab79befac972c9ae0517b1196c3/libp2p/protocols/identify.nim#L149

Looks there, is it incomplete ?

**Comment by dryajov** [comment]
Yah, it's just a stub. Still needs to be added.

**Comment by sinkingsugar** [comment]
Alright, I will have a deeper look at it!

**Comment by sinkingsugar** [comment]
@dryajov , I'm a bit confused on how you are supposed to subscribe to this push event.
> The push variant works by opening a stream to each remote peer you want to update
How do we know which ones we want to update?

**Comment by sinkingsugar** [comment]
Looks like that only the `js` implementation has it fully working/defined:
https://github.com/libp2p/js-libp2p/blob/f662fdcf3643f6975e39111e2ffb610de96d7958/src/identify/index.js#L102

**Comment by dryajov** [comment]
> @dryajov , I'm a bit confused on how you are supposed to subscribe to this push event.
> 
> > The push variant works by opening a stream to each remote peer you want to update
> 
> How do we know which ones we want to update?

Basically as it states; it should negotiate an identify push channel for each peer that supports it (using `multistream.select()`) and then send updates every time something changes, usually the peer's addresses/protocols. This is useful when roaming between different networks, etc...

**Comment by Menduist** [comment]
I've started to implement this, but it seems that the PeerStore should be finished before the push identify?
In the current state, there is nothing to update (since the PeerInfo is lost at the end of the connection anyway), and no one to push the update to (since we don't keep a book of the known peers).

Unless I've missed something?

I'll pause this and get started on the PeerStore

**Comment by dryajov** [comment]
Hmm good point, but for now I think we can expose events to notify of the changes, later on we can hook this events to the peerstore. So instead of passing the peerstore around I would just expose `onPeerChanged` (or something similar) on the switch, like we do with other peer events.

**Comment by Menduist** [comment]
Closed by #587
