### ISSUE TITLE
Multi Transport Support

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#496]
# Multi Transport Support

Currently nim-libp2p only supports one transport type due to the way connection upgrades happen, which is monolithic and assumes the need for arbitrary components, such as a multiplexer. On top of that, the switch has grown into a sort of a god object that mixes all sorts of discreet steps, such as dialing, upgrading, securing and muxing, into a single step. This limits the ability to plug other transports, besides those that assume a multiplexer, easily.

In order to enable multi-transport support in libp2p, we need to refactor the switch to do less and make the transports responsible of their own upgrade flow. Switch needs to be broken up into several components, so far I've tentatively come up with:

- [x] An "Upgrade Manager", that will allow transports to build/plug their own upgrade flow
- [ ] A dialer that will perform more sophisticated dialing logic. This isn't strictly required for multi-transport support, however it relieves the switch from having to implement this functionality. That said, we can leave this part in the switch initially
- [ ] Most of what the switch does now in terms of driving the upgrade flow, needs to move down to the transports. Of course each transport will have a slightly different set of requirements, but most of that logic can and should be contained in the `transport.nim` module, with the relevant parts specialized in each transports.

**Comment by dryajov** [comment]
The "Upgrade Manager" refactor has been addressed in #507

**Comment by Menduist** [comment]
Now supported
