### ISSUE TITLE
Move away from manual protobuf handling

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#50]
Currently all protobuf messages are handled manually using https://github.com/status-im/nim-libp2p/blob/master/libp2p/protobuf/minprotobuf.nim. This is tedious and error prone. 

TODO:
- Investigate or implement an alternative to minprotobuf.

**Comment by sinkingsugar** [comment]
Protobuf are a curse to humanity but I guess we have no choice.
Any reason not to use directly the real protobuf?
Some brain food:
1. Can add compile time nim procs/scripts to deal with the foreign part transparently, only issue is nimble unable to fetch external dependencies.
2. Rust has an amazing crate https://github.com/danburkert/prost
3. Nim has an unstable and hardly complete https://github.com/PMunch/protobuf-nim

**Comment by arnetheduck** [comment]
well, we have a simple use case for now and are just following existing protocols - using a code generator or complicated macro library doesn't really make that much of a difference in practical terms for the trivial things we need - weigh that against the increased complexity in build system or trying to understand/debug what that black box of generated code actually does.

at it's core, protobuf is a stream of key-value pairs with some simple varint/tlv encoding - it's all the fluff around it that makes it easy to lose this perspective.

**Comment by dryajov** [comment]
We might revisit this once a good protobuf implementation is available.
