### ISSUE TITLE
Deduplicate messages in pubsub/gossipsub `rpcHandler`

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#524]
Currently, we're deduplicating messages per message type, for example `iHave`, we should deduplicate messages once in the RPC handler. Additionally, it makes sense to re-evaluate scoring for peers sending large number of duplicates. 

A related issues has been identified in #400.

**Comment by Menduist** [comment]
We are now more strict about peers sending duplicates (#920)
