### ISSUE TITLE
Revisit Floodsub

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#525]
Currently, the state of `Floodsub` is unknown even with the current coverage we have. For `v1` we need to make sure that the current implementation is at least minimally functional.

**Comment by sinkingsugar** [comment]
Tests are passing, we got coverage and well the implementation overall is very simple. What do you suggest we should do further about it?

**Comment by dryajov** [comment]
I believe @oskarth ran into an issue with it a while back, but has since switched to gossip in waku. @oskarth do you happen to remember (or perhaps captured) the issue that you ran into with floodsub?

**Comment by oskarth** [comment]
I don't remember the details, it had something to do with topic subscription management I think? Here is some context: https://github.com/status-im/nim-waku/issues/161 and https://github.com/status-im/nim-waku/pull/157

**Comment by sinkingsugar** [comment]
Thanks @oskarth , that's indeed an issue in the inheritance tree. 
`GossipSub` and `FloodSub` are not final so inheriting is fine but they exclude each-other in terms of internals.

**Comment by arnetheduck** [comment]
maybe they should be refactored so they don't inherit - I find it pretty confusing tbh

**Comment by sinkingsugar** [comment]
I agree, I would have preferred composition anyway, the point of inheritance is basically to allow floodsub peers to connect if wanted.

**Comment by sinkingsugar** [comment]
I hardly think this refactor is something required for v1 tho.. gossipsub is preferred and superior in any case... sounds almost like secio and noise to me

**Comment by sinkingsugar** [comment]
Coverage is 77%, maybe add more coverage before closing this.
