### ISSUE TITLE
Revisit documentation and coding examples

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#526]
This is a meta issue to track user documentation and code example quality. Currently, both are very rudimentary and need an overall improvement. In addition, our code is poorly documented and needs a thorough revamp.

**Comment by sinkingsugar** [comment]
Interesting, I completely forgot about the `docs` folder, all I see is many empty `.md` files. Not sure exactly what to do about it.
I will make sure there is no deprecated/outdated code samples for now.

**Comment by dryajov** [comment]
> Interesting, I completely forgot about the `docs` folder, all I see is many empty `.md` files. Not sure exactly what to do about it.
> I will make sure there is no deprecated/outdated code samples for now.

Lets get rid of the docs dir for now and make sure that the code is well commented. That's the best we can do at the moment.

**Comment by sinkingsugar** [comment]
Btw It's a bit more complicated than that, there are some reference to that docs folder in those
https://our.status.im/nim-libp2p-tutorial-a-peer-to-peer-chat-example-1/ ?
Which btw are now outdated...
