### ISSUE TITLE
Gossip disconnect peers regardless of presence of `sendConn`

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-libp2p#532]
Currently, gossip drops peers only if there is a `sendConn` - 

https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/gossipsub/scoring.nim#L85-L91

We should always disconnect peers with low scores regardless of the existence of a send connection, otherwise this peers are still using up connection slots, which means that we won't be able to connect to new peers.

**Comment by sinkingsugar** [comment]
Ok sure, thanks, but we would a peer exist without a send connection? the protocol would not work (gossip)

**Comment by sinkingsugar** [comment]
> Ok sure, thanks, but why would a peer exist without a send connection? the protocol would not work (gossip)

**Comment by dryajov** [comment]
> Ok sure, thanks, but why would a peer exist without a send connection? the protocol would not work (gossip)

Peers that connect to us don't necessarily have a send connection. In other words, a remote peer might connect to gossipsub and send us messages without us having a send connection. The send connection only gets established when we broadcast.

**Comment by sinkingsugar** [comment]
I know what you mean, it's allowed by the library and mplex but gossip itself will likely always have duplex communication.
Anyway.
This has been fixed. That's why I closed it. And I'll close again.

**Comment by sinkingsugar** [comment]
https://github.com/status-im/nim-libp2p/commit/922cd92f94cfa61229433c367c68a62524beab31 for ref
