### ISSUE TITLE
`handlePrune()` potentially overflows `int64`

### ISSUE THREAD

**Issue by tersec** [status-im/nim-libp2p#538]
https://github.com/status-im/nim-libp2p/blob/c1334c6d89f6b2ee17f8fb135dcfa7600a806442/libp2p/protocols/pubsub/gossipsub/behavior.nim#L173-L177

`prune.backoff` itself, though it's a `uint64`, comes from a `int64`, but if it's already near `high(int64)`, then `backoff + 2` can overflow the `int64` conversion here.

**Comment by sinkingsugar** [comment]
I find `Moment` confusing indeed. Thanks.

**Comment by sinkingsugar** [comment]
Isn't the issue here mostly that `Moment` can be negative for no good reasons?
https://github.com/status-im/nim-chronos/blob/03707426e43d03cccc1de2e7284de168b79f7bf6/chronos/timer.nim#L181

**Comment by sinkingsugar** [comment]
well int64 is good for 580 years it seems.. so I'm not sure if this issue is relevant.
https://news.ycombinator.com/item?id=14174958

**Comment by tersec** [comment]
Feel free to close, consider complete, and/or not relevant. Wanted to document it though.

**Comment by sinkingsugar** [comment]
let's do some overflow checking anyway, altho in this case is against a constant so maybe its safe.
Btw is this related to new compiler? does some warning?

**Comment by sinkingsugar** [comment]
(closed by mistake btw)

**Comment by tersec** [comment]
Yes, it's because Nim 1.2.10 includes https://github.com/nim-lang/Nim/issues/15210
