### ISSUE TITLE
repeated uint32 are not decoded correctly.

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-libp2p#561]
A message with the following format, encoded with https://buf.build/ (in js), or https://github.com/gogo/protobuf (go) is not decoded correctly with `minprotobuf.nim`
```js
message TheMessageName {
  repeated uint32 theAttribute = 1;
}
```
```nim
var value seq[uint32]
let res1 = pb.getRepeatedField(1, value)
# res1 is false
# value is @[] (empty)
```

The problem seems to be related to the data type `uint32`, because if it's changed to `string` the decoding returns the expected result.

**Comment by sinkingsugar** [comment]
I think you have to use `getRepeatedField` and not `getField`.

**Comment by richard-ramos** [comment]
Yes, sorry, my example was incorrect, the issue happens with `getRepeatedField` not with `getField`.
I edited the issue description to have the correct function.

**Comment by sinkingsugar** [comment]
@cheatfate do you have any idea about this?

**Comment by cheatfate** [comment]
@richard-ramos could you please provide sequence of bytes which is not decoded properly? Because right now you only point to some links which do not help to reproduce a problem.

**Comment by cheatfate** [comment]
For example binary sequence of `080008FFFFFFFF0708FFFFFFFF0F088080808008` was successfully decoded using this sample:

```nim
import minprotobuf
import std/strutils
import nimcrypto/utils

var pb1 = initProtoBuffer()
pb1.write(1, 0x00'u32)
pb1.write(1, 0x7FFF_FFFF'u32)
pb1.write(1, 0xFFFF_FFFF'u32)
pb1.write(1, 0x8000_0000'u32)
pb1.finish()
echo toHex(pb1.buffer)
var pb2 = initProtoBuffer(pb1.buffer)
var fieldarr1: seq[uint32]
let r1 = pb2.getRepeatedField(1, fieldarr1)
echo r1
for item in fieldarr1:
  echo toHex(item)
```

protoc is also able to decode this binary sequence properly:
```
cat uint32.bin | protoc --decode_raw
1: 0
1: 2147483647
1: 4294967295
1: 2147483648
```

**Comment by arnetheduck** [comment]
@cheatfate probably packed encoding: https://developers.google.com/protocol-buffers/docs/encoding#packed

**Comment by cheatfate** [comment]
@arnetheduck i can assume many things from original issue message by @richard-ramos 
1. Used `proto3` instead of `proto2` which is supported by `minprotobuf.nim`.
2. Somebody forgot about that packet fields should be annotated in `TheMessageName` with `[packed=true];`.
3. `uint32` array expected, but original binary sequence has `uint64` values.
4. Incorrect binary sequence passed

So there is a lot of different scenarios which could happened.

**Comment by richard-ramos** [comment]
I'm using `proto3`

Example byte array: `@[byte(10),3,10,20,30]`

Here's an example nim code that I used to test
```nim
import libp2p/protobuf/minprotobuf
var pb1 = initProtoBuffer(@[byte(10),3,10,20,30])
var fieldarr1: seq[uint32]
let r1 = pb1.getRepeatedField(1, fieldarr1)
echo r1
for item in fieldarr1:
  echo item
```
I wasn't aware there was a `getPackedRepeatedField` function, which effectively "fixes" the issue. Having to read libraries source code to learn the existence of functions is not ideal. Adding some documentation to these libraries (even in the form of a simple README.md) could certainly improve the dev experience
