### ISSUE TITLE
Support for ping protocol

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-libp2p#567]
`nim-libp2p` currently does not support [ping protocol](https://docs.libp2p.io/concepts/protocols/#ping)

There are several reasons why this may be a useful protocol to add, including:
1. To perform simple connectivity and aliveness checks, especially for long-lived connections
2. To be used in keep-alive mechanisms that prevent streams from timing out (see for example [this issue](https://github.com/status-im/nim-waku/issues/504) where a connection times out if peers are idle)

Protocol id is `/ipfs/ping/1.0.0`

There are reference implementations in [go](https://github.com/libp2p/go-libp2p/tree/master/p2p/protocol/ping), [js](https://github.com/libp2p/js-libp2p/tree/master/src/ping) and [rust](https://github.com/libp2p/rust-libp2p/tree/master/protocols/ping)

cc @oskarth @D4nte

**Comment by oskarth** [comment]
cc @dryajov for thoughts on how important this is for nim-libp2p roadmap, in general

**Comment by dryajov** [comment]
This is definitely not on the critical path. However, this is definitely useful and should be added at some point. The bonus is that this should be relatively simple to implement and a good first issue for anyone looking to contribute.

**Comment by Menduist** [comment]
Closed by #584
