### ISSUE TITLE
Handling of asymmetrical protocols

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-libp2p#568]
Following from @D4nte's [question](https://github.com/libp2p/specs/issues/324) in `libp2p`, it appears libp2p best practice provisions for asymmetrical protocols where peers participating in the same protocol, but in different roles, may choose to differentiate between their roles by:
1. Sending differentiated protocol IDs in the `identify` protocol list, or
2. Excluding that protocol from the `identify` protocol list

See [this comment](https://github.com/libp2p/specs/issues/324#issuecomment-831831003) for examples of the above

Is this something supported by `nim-libp2p`? In other words, is it possible to `mount` a protocol but choose not to include that in the `identify` protocol list?

**Comment by dryajov** [comment]
> Is this something supported by nim-libp2p? In other words, is it possible to mount a protocol but choose not to include that in the identify protocol list?

Yes, both are supported. If a protocol shouldn't be advertised it is simply not mounted. I would use this two techniques in different situations however.

- If a protocol has a pure client/server mode and the client shouldn't handle requests, then don't mount the protocol for the client
- if a protocol a node can assume explicit modes of operation, as it is the case of the `hop/stop` parts in the relay, then I would use the second technique with different protocol strings

Fun fact, the changes suggested for relay v2 was what got originally proposed but rejected with the argument that "libp2p protocol strings aren't REST endpoints" 🤔 - glad to see it come full circle ;-)

**Comment by Menduist** [comment]
Closing, feel free to re-open if needed
