### ISSUE TITLE
Support for DNS addresses

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-libp2p#571]
## Problem statement

The [multiaddr specification](https://github.com/multiformats/multiaddr) specifies support for `dns4`, `dns6` and `dnsaddr` addresses. It is possible to [create and parse such addresses](https://github.com/status-im/nim-libp2p/blob/master/libp2p/multiaddress.nim#L407) in the Nim implementation, but there is currently no way to resolve these to dialable transport addresses. Clients trying to connect to a DNS address will encounter an [Invalid Address exception](https://github.com/status-im/nim-libp2p/blob/master/libp2p/wire.nim#L91).

DNS address resolution will be a useful feature to add for clients not using static IPs.

## Acceptance criteria

- [ ] Add a resolver for DNS multiaddrs (`dns4`, `dns6` and `dnsaddr`)

## References

- Reference resolver implementations in [js](https://github.com/multiformats/js-multiaddr/blob/master/src/resolvers/index.js) and [go](https://github.com/multiformats/go-multiaddr-dns).
- `dnsaddr` specification [here](https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md)

cc @dryajov in case this has already been discussed in a different context

**Comment by Menduist** [comment]
Done in #615
