### ISSUE TITLE
The transport system doesn't allow multiple local addresses

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-libp2p#597]
Currently, each transport is `start`ed [for each supported address](https://github.com/status-im/nim-libp2p/blob/72ccd1d1f55764df35087b063ed38f688f517d6a/libp2p/switch.nim#L365).

This is wrong, because a transport _could_ handle multiple local address: eg, if bound to multiple local addresses, bound to multiple ports, or ipv4+ipv6.
In the current form, a transport handling multple addresses starts & stops multiple time, ignoring extraneous addresses, causing exceptions in some cases.

Not sure what is the best way to solve this, inputs are welcomed.

My ideas:
- Make each transport handle multiple addresses instead of one (each transport will have to start multiple servers, have a accept loop for each server, etc). Not a big fan of this, because this will lead to duplicated logic for each transport
- Transform the transports into factories, which are called for each applicable address. The only issue I see with this is that the `handles` method will be used both in the factory and the actual transport. Not too big a deal
- ?

I've created a branch to work on this, currently I just added a test case for this issue: https://github.com/status-im/nim-libp2p/commit/3a05eba0e72e97927bef43da870f091f86af18ef

cc @dryajov @markspanbroek

**Comment by dryajov** [comment]
@Menduist I've added support for multiple transports here - https://github.com/status-im/nim-libp2p/pull/598. I had a very clear mental image of how it would be done for a while and it made sense to just write the code first - but please feel free to leave feedback, etc...

**Comment by Menduist** [comment]
Closed by #598
