### ISSUE TITLE
Various cleanups

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-libp2p#620]
Some groundwork for V1:

- [ ] Mount PushIdentify by default in `newStandardSwitch`
- [x] Try to remove as much exported procs & fields as possible
- [x] Remove `raise` without explicit exception (should be `raise exc`)
- [x] Check that we don't try to catch `RangeError` (or other defects)
- [x] Remove the need for stdlib random
- [x] Check the `new`/`init` procs
- [x] Remove deprecated procs
- [x] Fix compilation warnings
- [x] Try to lower the recursive dependency count as low as possible

**Comment by arnetheduck** [comment]
>  Mount PushIdentify by default in newStandardSwitch

we've avoided any strictly unnecessary protocols so as to reduce the security surface area and information leaks in the "default" setup - by not having them enabled, users of libp2p are made aware of each protocol that they're enabling so they can analyze its usefulness for their application - eth2 for example likely  shouldn't have it enabled

**Comment by Menduist** [comment]
Done except the Push Identify
