### ISSUE TITLE
Don't relay to any peer that has seen message already

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#626]
https://github.com/status-im/nim-libp2p/pull/625 fixes message relay such that message is never sent to the source peer that obviously already has it.

However, because validation is asynchronous and can take time, it's quite possible that a message is received from multiple peers while it's being validated - sending the message to any of these peers is a waste.

**Comment by dryajov** [comment]
Good point, we should filter out peers that have already notified us that they've seen the message (`IHAVE`) - we might be already doing that but I don't remember, something to check - @Menduist

**Comment by Menduist** [comment]
> Good point, we should filter out peers that have already notified us that they've seen the message (IHAVE)

That would not happen, because peers in our mesh don't send us IHAVEs

**Comment by dryajov** [comment]
> That would not happen, because peers in our mesh don't send us IHAVEs

Why? It should - this is per the [spec](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md#gossipsub-the-gossiping-mesh-router):

> To allow peers to "reach beyond" their mesh view of a topic, we use gossip to propagate metadata about the message flow throughout the network. This gossip is emitted to a random subset of peers who are not in the mesh. We can think of the mesh members as "full message" peers, to whom we propagate the full content of all messages received in a topic. The remaining peers we're aware of in a topic can be considered "metadata-only" peers, to whom we emit gossip at regular intervals.

> The metadata can be arbitrary, but as a baseline, we send the IHAVE message, which includes the message ids of messages we've seen in the last few seconds. These messages are cached, so that peers receiving the gossip can request them using an IWANT message.

**Comment by Menduist** [comment]
https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.0.md#gossip-emission

```
    for each peer not in mesh[topic] or fanout[topic]
      emit IHAVE(mids)
```

If the peer is in our mesh, we already sent him every message we received, there is no point to send him IHAVE

**Comment by Menduist** [comment]
Done in https://github.com/status-im/nim-libp2p/pull/648
