### ISSUE TITLE
Feat: Implement PING example in nim-libp2p from rust-libp2p

### ISSUE THREAD

**Issue by muddlebee** [status-im/nim-libp2p#686]
Implement PING example in nim-libp2p from rust-libp2p

https://github.com/libp2p/rust-libp2p/blob/master/examples/ping.rs

**Comment by Menduist** [comment]
Hi, you'll find something similar here: https://github.com/status-im/nim-libp2p/blob/master/examples/tutorial_1_connect.md

**Comment by muddlebee** [comment]
hey @Menduist thanks.

I was exploring nim-language and nim-libp2p. Goal of this feature was to get a hands on with nim-lang and get the idea of nim-libp2p so that it helps me in contributing to other eth-1/2 projects :) 

Will it be okay if I implement some of the examples from https://github.com/libp2p/rust-libp2p/tree/master/examples to here? to get a learning grasp and also some value added here at nim-libp2p?

**Comment by muddlebee** [comment]
Also I am pariticipating in Ethereum Core Developer Apprenticeship program https://blog.ethereum.org/2021/09/06/core-dev-apprenticeship-second-cohort/ . So I found the status projects for contribution.

**Comment by Menduist** [comment]
> Will it be okay if I implement some of the examples from https://github.com/libp2p/rust-libp2p/tree/master/examples to here?

Of course, any contribution is welcomed :)
From your link, we already have a ping & chat examples, but you're welcome to revisit them if you want

Note that we currently don't have a DHT implementation (it's in progress), which may limit you for some of the examples
