### ISSUE TITLE
Connection.readLP not protected against unreasonable sizes

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#69]
https://github.com/status-im/nim-libp2p/blob/691efaa8a12a4055719fd9fb1b91b46e1944c12a/libp2p/connection.nim#L112

since the remote end sends a size first, it can force the application to try to allocate ridiculous amounts of memory - should require a max length.

**Comment by cheatfate** [comment]
@arnetheduck but it is covered with check for ```size < DefaultReadSize```.

**Comment by arnetheduck** [comment]
right, missed it

**Comment by sinkingsugar** [comment]
Btw this is kinda wrong, the value of `DefaultReadSize` is not in the spec, and prevents `mplex` 1MB max size messages too.
See: https://github.com/status-im/nim-libp2p/pull/74#issuecomment-583686355
Also chronos seems to fail with big sizes in stream transport somehow https://github.com/status-im/nim-chronos/issues/72
