### ISSUE TITLE
Distinguish graceful EOF from other disconnects

### ISSUE THREAD

**Issue by etan-status** [status-im/nim-libp2p#755]
When functions like `readExactly` indicate `EOF`, it is not possible to distinguish:
- Graceful `close` from remote side
- `reset` from remote side / other connection issue

In Ethereum consensus specs, `beacon_blocks_by_range` and `beacon_blocks_by_range` do not distinguish:
- All requested slots are empty
- Peer does not have data available about requested range

Therefore, we convert to `PotentiallyExpectedEOF` in `nimbus-eth2 > eth2_network.nim`
```
    var responseCodeByte: byte
    try:
      await conn.readExactly(addr responseCodeByte, 1)
    except LPStreamEOFError, LPStreamIncompleteError:
      return neterr PotentiallyExpectedEOF
```

This treats EOF as a valid result for those requests, effectively hiding any non-graceful reasons for EOF.
Having a way to distinguish graceful from non-graceful stream closures would allow more accurate peer scoring.

**Comment by lchenut** [comment]
It should be good now. Here's a table to indicate which error is raised in each case. All errors inherit from LPStreamEOFError (for backward compatibility).
```
X     | Remote reset       | Local reset         | Remote close              | Local close         | Connection down    
--------------------------------------------------------------------------------------------------------------------------
Read  | LPStreamResetError | LPStreamClosedError | LPStreamRemoteClosedError | Works               | LPStreamConnDownError
Write | LPStreamResetError | LPStreamClosedError | Works                     | LPStreamClosedError | LPStreamConnDownError
```
