### ISSUE TITLE
Hole punching

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-libp2p#826]
Requires:
- https://github.com/status-im/nim-libp2p/pull/739
- https://github.com/status-im/nim-libp2p/pull/717
- https://github.com/status-im/nim-libp2p/pull/814
- https://github.com/status-im/nim-libp2p/pull/819
- https://github.com/status-im/nim-libp2p/pull/824
- https://github.com/status-im/nim-libp2p/pull/806
- https://github.com/status-im/nim-libp2p/pull/873
- https://github.com/status-im/nim-libp2p/pull/871
- https://github.com/libp2p/specs/blob/master/connections/simopen.md ?

**Comment by Menduist** [comment]
@diegomrsantos should we mark this as done?

**Comment by diegomrsantos** [comment]
> @diegomrsantos should we mark this as done?

The basic flow has been implemented, but it hasn't been fully tested in production yet.

> @diegomrsantos should we mark this as done?

**Comment by diegomrsantos** [comment]
Let's close this now that https://github.com/status-im/nim-libp2p/pull/998 has been finished. We also need to enable it in a test network, but it'll be done later and we can open new issues if they arise during deeper testing.
