### ISSUE TITLE
gossipsub: lazy prefix detection

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#859]
Consider the following case:

* we receive a message from peer A and start validating it
* we start receiving a message from B and store the first N bytes in an "in-flight" map
* we finish validating and are ready to re-broadcast to peer B which is in our mesh

At this point, if the message we're about to send matches any "in-flight" entry, delay sending the message to that peer so as to potentially avoid a duplicate send.

This is expected to work well for larger messages whose prefixes typically are unique.

**Comment by Menduist** [comment]
An alternative to this might be to send (if the message is big enough to warrant this):
- IHAVE <msgid>
- <msg id content>

The the other side can know who has it, before even sending receiving the full message once.
Requires small spec change though

**Comment by arnetheduck** [comment]
> Requires small spec backward-compatible change though

hm, the question here is what happens when a peer receives `IHAVE` for a message they don't have, but is inflight from other peers - it doesn't _quite_ make sense to query for it with IWANT for example - there's a semantic difference: "I have the message and will now send it to you" vs "I have the message, come and ask for it" that drives a difference in response as well, potentially

**Comment by Menduist** [comment]
Sure, maybe that should instead be a new field in the protobuf, which would make backward compatibility even better (if you don't support this extension you'll just ignore it)
