### ISSUE TITLE
Create a default mechanism to populate peerInfo.addrs

### ISSUE THREAD

**Issue by diegomrsantos** [status-im/nim-libp2p#863]
Currently, there are two lists of addresses in `PeerInfo`: `listenAddrs` and `addrs`. `listenAddrs` is the list of addresses the peer is listening to. It may contain any kind of IP, private or not. `addrs` is the peer's dialable addresses list. At the moment, nim-libp2p just copies the former list to the latter. It's the application's job to create an `AddressMapper`, process `listenAddrs` and modify `addrs` as it wishes. 

In this task, we will create a default mechanism for populating `addrs` with dialable addresses. There will be a flag which applications can use to disable this mechanism if they wish to use an `AddressMapper` instead. 

There are two things we need to find out about a dialable address: its public IP and port. Additionally, there are two scenarios we need to consider: If we are behind a NAT or not. You might ask why would a peer want to advertise its dialable addresses if it is behind a NAT. The answer is to hole punch.

### Finding our public port

The port used to start the transport will be the same as other peers must use to dial us, so this case is straightforward. 

### Finding our public IP
 
If the application was started with public IPs, we can just use them. But if "0.0.0.0" or "::1" was used, we can learn our public IP by using the following proc: `getBestRoute(initTAddress(<public-ip>)).source.host`. For IPv6 we can use the "2600:::0" global random IP and for IPv4 something like "8.8.8.8."

### Finding our public Port

The current proposal is to always reuse ports when creating outgoing connections, i.e. binding the socket to the same port the peer is listening to before dialling. In this way it is likely the port used on the NAT will be the same and we can learn about it through the observed address in the Identify message. 

For now, we will support only TCP Transport. There can be one or more IPv4 and/or IPv6 listening addresses in a TCP Transport. As we store the listening addresses in an ordered data structure, we will always use the first listening address matching the dialled address IP version as the binding address.

In this way, the observed pairs of IPs and ports which the remote peers will report to us can be used to build our list of dialable addresses.

**Comment by Menduist** [comment]
This has been done? Feel free to re-open otherwise @diegomrsantos
