### ISSUE TITLE
feat: expose connections, streams and protos

### ISSUE THREAD

**Issue by alrevuelta** [status-im/nim-libp2p#866]
Would be nice to expose the `conns` of the `ConnManager` so that one can get more information about the active connections/streams, such as `transportDir` or `protocol`. Since the [field](https://github.com/status-im/nim-libp2p/blob/unstable/libp2p/connmanager.nim#L78) is currently not exposed this is not possible right now. Perhaps also `muxed`.

For example, lets say an app is using nim-libp2p and wants to know the number of active connections using a given protocol. Or number of active connections using a given protocol that are inbound to the node?

cc @Menduist

**Comment by diegomrsantos** [comment]
I would suggest exposing procs that give the information needed instead of making the private fields public.

**Comment by alrevuelta** [comment]
@diegomrsantos that also works for me. As long as the content is available, I'm happy with any solution that accomplishes that :)
