### ISSUE TITLE
Don't send duplicate messages to IHAVE-announcing peers

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-libp2p#867]
As a subset of #859, we should not be rebroadcasting messages to peers that have announced they have it via IHAVE - this applies for IHAVE's received during async validation in particular

**Comment by Menduist** [comment]
Peers don't sent IHAVEs to peers inside their mesh, so that situation shouldn't happen currently

My proposal https://github.com/status-im/nim-libp2p/issues/859#issuecomment-1425574521 here assumes a slight spec change to send IHAVE to peers in mesh for big messages
