### ISSUE TITLE
IWANT replies can be bigger than the pubsub message limit

### ISSUE THREAD

**Issue by alrevuelta** [status-im/nim-libp2p#887]
I'm a bit confused by this log. It says that msgSize=4950305 (5MB) but I'm sure that all the messages im publishing are exactly 0.9 MB. So is this log related to gossipsub? or some other type of "message" (perhaps lower level?)

```
trying to send a too big for pubsub        topics="libp2p pubsubpeer" tid=1 file=pubsubpeer.nim:248 maxSize=1048576 msgSize=4950305
```

**Comment by Menduist** [comment]
This is probably caused by an IWANT reply which may bundle multiple messages
Need to split messages when we are oversized, and check that go & co does the same
