### ISSUE TITLE
Socket Leak in nim-libp2p leading to File Descriptor Exhaustion

### ISSUE THREAD

**Issue by diegomrsantos** [status-im/nim-libp2p#973]
We have identified a persistent socket leak issue within the nim-libp2p library while running a nimbus instance. This issue becomes evident when there's network disconnection or peer disconnection; the socket descriptors aren't being released correctly, leading to an accumulation over time. This behavior can potentially exhaust the available file descriptors, especially in environments with a file descriptor limit set (e.g., 15k in our case).

Upon investigating, it was found that a related issue was present in the chronos library, where an exception during the cleanup process would halt the cleanup, leading to leaks. This issue in chronos was recently addressed (Refer: [Chronos Fix PR](https://github.com/status-im/nim-chronos/pull/445/files#diff-3a79eddc35c05d42f083797ba12d93595708c9ceb8a21b68c8faeb74054113dfR785)). Additionally, corresponding fixes were made in the nimbus-eth2 repository to handle stream leaks (Refer: [Nimbus Eth2 Fix Commit](https://github.com/status-im/nimbus-eth2/commit/caaad4777c620fc414f7b0622dc083ef0da66c5e)).

However, despite these fixes, the socket leak in nim-libp2p persists. The expectation is that, upon a peer disconnection or network disconnection event, the number of socket descriptors should decrease correspondingly, reflecting in a zig-zag pattern on monitoring graphs. However, the current behavior shows a continuous growth in the number of socket descriptors over time.

This issue necessitates a thorough review and potential rewrite of the socket handling and cleanup processes in nim-libp2p, to ensure that sockets are being closed and descriptors are being released correctly, especially during disruptive events like peer disconnections. The aim is to align the socket descriptor pattern on both sides of the connection, ensuring that any disconnection event on one side results in a corresponding file descriptor release on the other.

Potential solutions could explore utilizing the noCancel functionality during the socket shutdown processes to ensure that cleanup is completed even when exceptions are encountered.

**Comment by arnetheduck** [comment]
If I were to guess, I'd start looking at dialling and its timeouts which are an obvious source of exceptions and cancellations in combination.

**Comment by arnetheduck** [comment]
I looked more deeply into the socket leaks and it turns out that this was running an older version that didn't have the chronos http fix - closing for now, will reopen if need be - regardless, auditing cancellation for the above issues is probably reasonable for libp2p to do - thanks for taking a look.
